[files]
extend-exclude = [".git", "**/.ipynb_checkpoints"]
ignore-hidden = false

[default]
check-filename = true
check-file = true
binary = false
locale = "en"
unicode = true

[type.ipynb]
extend-glob = ["*.ipynb"]
extend-ignore-identifiers-re = ["ges", "nd"]
