version: 2

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.13"

sphinx:
    configuration: docs/conf.py
    fail_on_warning: true

formats:
  - pdf

python:
    install:
      - method: pip
        path: poptus_pypkg
